### ISSUE TITLE
Duplicates in BigQuery

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/bigquery#82] opened 2020-06-22 08:36 UTC
Hi folk,

There are too many duplicates in _technology_ tables. For example in many rows WordPress is as _CMS_ and _BLOG_ stored for same URL. There are also some JavaScript Libraries which are as JavaScript Framework and Library stored. In these duplicates, just the category name is different. I think these duplicates should be removed in next releases (at least) .

**Comment by rviscomi** [comment] 2020-06-22 18:15
Could you share a query that's giving you trouble? I can suggest a couple of techniques for deduplicating the results.

**Comment by nrllh** [comment] 2020-06-23 07:30
For my project i just used select and query all data in a table. I can use group by for deduplicating but shouldn't HTTPArchive remove duplicates while creating the dataset?

**Comment by rviscomi** [comment] 2020-06-24 22:51
It'd be helpful if you could provide a query to reproduce the duplicates you're seeing.

In this query I'm counting the number of duplicate category/app combinations for each URL and there is only one page that has duplicates, because the app names are undefined.

```sql
SELECT
  url,
  category,
  app,
  COUNT(0) AS duplicates
FROM
  `httparchive.technologies.2020_05_01_desktop`
GROUP BY
  url, category, app
HAVING
  duplicates > 1
ORDER BY
  duplicates DESC
```

**Comment by nrllh** [comment] 2020-06-24 23:31
Here a query based on yours:


```
SELECT
  url,
  app,
  info,
  COUNT(0) AS duplicates
FROM
  `httparchive.technologies.2020_05_01_desktop`
WHERE
  info !=''
GROUP BY
  url, app, info
HAVING
  duplicates > 1
ORDER BY
  duplicates DESC
  
```

You can not find duplicates by grouping url, category and app. Because some of products are assigned to more categories.

**Comment by rviscomi** [comment] 2020-07-03 15:55
Having multiple categories for a given app is by design in Wappalyzer. Do you think this is a categorization problem in Wappalyzer or an issue with the way we're organizing the data in BigQuery? For example, we could aggregate categories into an array so there's one URL/app combination per row. I'm not sure how that would affect the ease of querying, it might be a bit more cumbersome. Ultimately I think it's just easier to group.

**Comment by nrllh** [comment] 2020-07-04 10:14
I don't know why Wappalyzer have for some software multiple categories, maybe I understand that a limitation is for some products hard.  
Grouping them is a solution but not everybody knows that there are multiple records and this can lead to wrong results.  
What about having multiple records for categories? Only TiddyWiki is in 4 categories, most of the other products have 2 or 3 categories.

**Comment by bazzadp** [comment] 2021-05-26 10:47
Closing this. Wappalzer chooses to categorise software under multiple categorie and I actually agree with that.

So if you change your query to include category there are no dupes for either 2020_05_01 nor 2021_05_01

```sql
SELECT
  url,
  app,
  category,
  info,
  COUNT(0) AS duplicates
FROM
  `httparchive.technologies.2020_05_01_desktop`
WHERE
  info !=''
GROUP BY
  url, app, category, info
HAVING
  duplicates > 1
ORDER BY
  duplicates DESC
```

Personally I don't agree with having multiple columns as it does limit us (only one thing is in 4 categories now but who knows if that will change).

But I do agree care must be taken to select DISTINCT URLs when querying this data.

**Closed by bazzadp** 2021-05-26 10:47 UTC
